
language: java
sudo: false
email: false

cache:
    directories:
        - $HOME/.m2

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gotztest;'

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P production

script: 
  - mvn clean

# in travis maven build - disable metrics server, ng-build profile and activate prod profile

after_success:
  - mvn verify jacoco:report coveralls:report -Dgotz.datastore.configFile=jdoconfig-mysql.properties -Dgotz.metrics.server.enable=false -P production 

jdk:
  - openjdk8
  - oraclejdk8

