
language: java
sudo: false
email: false

cache:
    directories:
        - $HOME/.m2

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gotztest;'

script: mvn clean

# in travis maven build - disable metrics server and deactivate ng-build profile

after_success:
  - mvn verify jacoco:report coveralls:report -Dgotz.datastore.configFile=jdoconfig-mysql.properties -Dgotz.metrics.server.enable=false -P -ng-build

jdk:
  - openjdk8
  - oraclejdk8

