version: "3"
services:
  db:
      image: mariadb:latest
      command: 
          --log_warnings=1
          --lower_case_table_names=1
          --innodb-compression-default=1
          --innodb_compression_algorithm=zlib
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=gotz
      ports:
          - "3306:3306"
      volumes:
          - ./data:/var/lib/mysql
          - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  gotz:
      image: maithilish/gotz:latest 
      depends_on:
          - db
      ports:
          - "9010:9010"
      volumes:
          - ./defs:/gotz/defs
          - ./conf:/gotz/conf
          - ./logs:/gotz/logs
          - ./output:/gotz/output
