//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.03.11 at 10:13:58 AM IST
//

package in.m.picks.model;

import java.util.Date;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public final class Adapter1 extends XmlAdapter<String, Date> {

    @Override
    public Date unmarshal(final String value) {
        return (in.m.picks.model.DateAdapter.parseDate(value));
    }

    @Override
    public String marshal(final Date value) {
        return (in.m.picks.model.DateAdapter.printDate(value));
    }

}
