//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.05 at 10:53:24 AM IST 
//

package in.m.picks.model;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringExclude;
import org.apache.commons.lang3.builder.ToStringStyle;


@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "document", propOrder = { "documentObject" })
public class Document extends Base implements Serializable {

	private final static long serialVersionUID = 1L;
	@ToStringExclude
	@XmlElement
	protected Object documentObject;
	@XmlAttribute(name = "fromDate")
	@XmlJavaTypeAdapter(Adapter1.class)
	@XmlSchemaType(name = "dateTime")
	protected Date fromDate;
	@XmlAttribute(name = "toDate")
	@XmlJavaTypeAdapter(Adapter1.class)
	@XmlSchemaType(name = "dateTime")
	protected Date toDate;
	@XmlAttribute(name = "url")
	protected String url;

	
	public Object getDocumentObject() {
		return documentObject;
	}

	
	public void setDocumentObject(Object value) {
		this.documentObject = value;
	}

	
	public Date getFromDate() {
		return fromDate;
	}

	
	public void setFromDate(Date value) {
		this.fromDate = value;
	}

	
	public Date getToDate() {
		return toDate;
	}

	
	public void setToDate(Date value) {
		this.toDate = value;
	}

	
	public String getUrl() {
		return url;
	}

	
	public void setUrl(String value) {
		this.url = value;
	}

	@Override
	public boolean equals(Object obj) {
		String[] excludes = { "id", "dnDetachedState", "dnFlags", "dnStateManager" };
		return EqualsBuilder.reflectionEquals(this, obj, excludes);
	}

	@Override
	public int hashCode() {
		String[] excludes = { "id", "dnDetachedState", "dnFlags", "dnStateManager" };
		return HashCodeBuilder.reflectionHashCode(this, excludes);
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this,
				ToStringStyle.MULTI_LINE_STYLE);
	}

}
