//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.03.12 at 11:35:17 AM IST
//

package org.codetab.gotz.model;

import java.util.Date;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1 extends XmlAdapter<String, Date> {

    public Date unmarshal(String value) {
        return (org.codetab.gotz.model.DateAdapter.parseDate(value));
    }

    public String marshal(Date value) {
        return (org.codetab.gotz.model.DateAdapter.printDate(value));
    }

}
