//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2017.06.29 at 12:23:21 PM IST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://codetab.org/gotz",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.codetab.gotz.model;
